DROP TABLE IF EXISTS [groups];
CREATE TABLE [groups] (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);
DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname VARCHAR(255) UNIQUE NOT NULL,
    group_id INTEGER NOT NULL,
    FOREIGN KEY (group_id) REFERENCES [groups] (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname VARCHAR(255) UNIQUE NOT NULL
);
DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    teachers_id INTEGER NOT NULL,
    FOREIGN KEY (teachers_id) REFERENCES teachers (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
DROP TABLE IF EXISTS grades;
CREATE TABLE grades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    students_id INTEGER NOT NULL,
    subjects_id INTEGER NOT NULL,
    date_of VARCHAR(255) NOT NULL,
    grade INTEGER NOT NULL,
    FOREIGN KEY (students_id) REFERENCES students (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
    FOREIGN KEY (subjects_id) REFERENCES subjects (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);